---

- name: ansible jenkins simple playbook
  hosts: all
  become: yes

  tasks:
      - name: here we install nginx and tree because not present earlier
        apt:
          name: "{{ item }}"
          state: present
          become: yes
          register: output
        ignore_errors: yes
        loop:
            - nginx
            - tree

      - name: printing output
        debug:
            var: output

      - name: checking status ufw firewall
        command: sudo ufw status
